"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useAtom } from "jotai";
import { brandAtom } from "@/atoms/brandAtom";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [branding, setBranding] = useAtom(brandAtom);

    useEffect(() => {
    const primary = branding?.primaryColor;
    const secondary = branding?.secondaryColor;
    const primaryDark = branding?.primaryColorDark;
    const secondaryDark = branding?.secondaryColorDark;
    
    if (primary) document.documentElement.style.setProperty("--brand-primary", primary);
    if (secondary) document.documentElement.style.setProperty("--brand-secondary", secondary);
    if (primaryDark) document.documentElement.style.setProperty("--brand-primary-dark", primaryDark);
    if (secondaryDark) document.documentElement.style.setProperty("--brand-secondary-dark", secondaryDark);
  }, [branding?.primaryColor, branding?.secondaryColor, branding?.primaryColorDark, branding?.secondaryColorDark]);


  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>{children}</body>
    </html>
  );
}
